### ISSUE TITLE
Missing Questions file

### ISSUE THREAD

**Issue by okspy47** [Bnux256/TheoryHelper#6]
The questions/questions.json file misses from the repo.  Can u at least provide a JSON template please?

**Comment by Bnux256** [comment]
Hi! Run `python3 lib/download_cache.py` to create the `questions/questions.json`.

**Comment by okspy47** [comment]
> Hi! Run `python3 lib/download_cache.py` to create the `questions/questions.json` file.

Thank you. I will try it as soon as I'm home.

**Comment by okspy47** [comment]
When trying the command, I'm getting this error at the part 18 of the cache:
![image](https://user-images.githubusercontent.com/72977006/234477124-1bf7ba6c-3f29-4ed2-93e2-22b2dd98dc6d.png)

**Comment by Bnux256** [comment]
What Python version are you using? Seems to be an issue with decoding... Here is my file if that's helpful (.csv because of Github uploads, rename file and change type to `.json`.
[questions.json.csv](https://github.com/Bnux256/TheoryHelper/files/11329626/questions.json.csv)

**Comment by okspy47** [comment]
Trying. Also cant do it with docker as it request me access and for some reason it says my account is incorrect

![image](https://user-images.githubusercontent.com/72977006/234503047-178d61fc-14ab-42ee-9ed1-9601ad5d0bca.png)

**Comment by Bnux256** [comment]
Before `docker compose up -d` run the build command: `docker build . -t bnux256/theoryhelper`. The readme had a mistake, sorry...

**Comment by okspy47** [comment]
I cant understand a bit of Hebrew. Can u make a smaller JSON with a few categories and questions, so I can understand the JSON better?
 Thanks in advance

**Comment by okspy47** [comment]
So, I thought that I can modify the JSON itself manually with Romanian questions

**Comment by Bnux256** [comment]
Sadly won't really work... Here are a few other projects which might be useful: 
[Anki](https://apps.ankiweb.net/) - Has spaced repetition and can import from Quizlet
[flashbang](https://flashbang.lol/)
[openmultiplechoice](https://github.com/openmultiplechoice/openmultiplechoice)
